import { Stage } from './types';

export const ETAPAS: Stage[] = [
  {
    id: 'Novo Lead',
    nome: 'Novo Lead',
    cor: 'text-blue-400',
    corBg: 'bg-blue-500/10',
    corBorda: 'border-blue-500/40',
    corHex: '#3B82F6',
    slaMinutos: 0.5,
    slaLabel: '30 seg',
  },
  {
    id: 'Triagem IA',
    nome: 'Triagem IA',
    cor: 'text-indigo-400',
    corBg: 'bg-indigo-500/10',
    corBorda: 'border-indigo-500/40',
    corHex: '#6366F1',
    slaMinutos: 10,
    slaLabel: '10 min',
  },
  {
    id: 'Qualificado',
    nome: 'Qualificado',
    cor: 'text-violet-400',
    corBg: 'bg-violet-500/10',
    corBorda: 'border-violet-500/40',
    corHex: '#8B5CF6',
    slaMinutos: 1440,
    slaLabel: '24h',
  },
  {
    id: 'Proposta Consulta',
    nome: 'Proposta Consulta',
    cor: 'text-pink-400',
    corBg: 'bg-pink-500/10',
    corBorda: 'border-pink-500/40',
    corHex: '#EC4899',
    slaMinutos: 1440,
    slaLabel: '24h',
  },
  {
    id: 'Agendando',
    nome: 'Agendando',
    cor: 'text-amber-400',
    corBg: 'bg-amber-500/10',
    corBorda: 'border-amber-500/40',
    corHex: '#F59E0B',
    slaMinutos: 120,
    slaLabel: '2h',
  },
  {
    id: 'Agendado',
    nome: 'Agendado',
    cor: 'text-orange-400',
    corBg: 'bg-orange-500/10',
    corBorda: 'border-orange-500/40',
    corHex: '#F97316',
    slaMinutos: 10080,
    slaLabel: 'Até consulta',
  },
  {
    id: 'Pago / Confirmado',
    nome: 'Pago / Confirmado',
    cor: 'text-emerald-400',
    corBg: 'bg-emerald-500/10',
    corBorda: 'border-emerald-500/40',
    corHex: '#10B981',
    slaMinutos: 1440,
    slaLabel: 'Até D-0',
  },
  {
    id: 'Compareceu',
    nome: 'Compareceu',
    cor: 'text-cyan-400',
    corBg: 'bg-cyan-500/10',
    corBorda: 'border-cyan-500/40',
    corHex: '#06B6D4',
    slaMinutos: 1440,
    slaLabel: '1 dia',
  },
  {
    id: 'No Show',
    nome: 'No Show',
    cor: 'text-red-400',
    corBg: 'bg-red-500/10',
    corBorda: 'border-red-500/40',
    corHex: '#EF4444',
    slaMinutos: 15,
    slaLabel: '15 min',
  },
  {
    id: 'Pós Consulta',
    nome: 'Pós Consulta',
    cor: 'text-teal-400',
    corBg: 'bg-teal-500/10',
    corBorda: 'border-teal-500/40',
    corHex: '#14B8A6',
    slaMinutos: 10080,
    slaLabel: '7 dias',
  },
  {
    id: 'Follow-up',
    nome: 'Follow-up',
    cor: 'text-purple-400',
    corBg: 'bg-purple-500/10',
    corBorda: 'border-purple-500/40',
    corHex: '#9333EA',
    slaMinutos: 4320,
    slaLabel: '3 dias',
  },
  {
    id: 'Retorno Marcado',
    nome: 'Retorno Marcado',
    cor: 'text-green-400',
    corBg: 'bg-green-500/10',
    corBorda: 'border-green-500/40',
    corHex: '#22C55E',
    slaMinutos: 43200,
    slaLabel: 'Até retorno',
  },
  {
    id: 'Recorrente',
    nome: 'Recorrente',
    cor: 'text-lime-400',
    corBg: 'bg-lime-500/10',
    corBorda: 'border-lime-500/40',
    corHex: '#84CC16',
    slaMinutos: 43200,
    slaLabel: 'Mensal',
  },
  {
    id: 'Perdido',
    nome: 'Perdido',
    cor: 'text-gray-400',
    corBg: 'bg-gray-500/10',
    corBorda: 'border-gray-500/40',
    corHex: '#6B7280',
    slaMinutos: 129600,
    slaLabel: '90 dias',
  },
  {
    id: 'Reativação',
    nome: 'Reativação',
    cor: 'text-rose-400',
    corBg: 'bg-rose-500/10',
    corBorda: 'border-rose-500/40',
    corHex: '#F43F5E',
    slaMinutos: 129600,
    slaLabel: 'Sazonal',
  },
];

export const ORIGENS = ['Instagram', 'Google', 'WhatsApp', 'Indicação'];
export const PRIORIDADES = ['urgente', 'alta', 'normal', 'frio'];

export const ETAPAS_ATIVAS = ETAPAS
  .filter(e => !['Perdido'].includes(e.id))
  .map(e => e.id);

export const SLA_MINUTOS: Record<string, number> = Object.fromEntries(
  ETAPAS.map(e => [e.id, e.slaMinutos])
);
